name: CI

on:
  push:
    branches: [ main, develop, release/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio
    
    - name: Run linting
      run: |
        pip install ruff black
        black --check src/ tests/ || true
        ruff check src/ tests/ || true
      continue-on-error: true
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short --maxfail=5 || true
      continue-on-error: true
    
    - name: Run security scan
      run: |
        python scripts/release_scan.py || true
      continue-on-error: true
    
    - name: Generate test report
      if: always()
      run: |
        echo "Test suite completed for Python ${{ matrix.python-version }}"
        echo "Check logs for detailed results"

  e2e:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup Playwright
      run: |
        pip install playwright
        playwright install chromium --with-deps
      continue-on-error: true
    
    - name: Run E2E tests
      run: |
        # E2E tests would go here if configured
        echo "E2E tests placeholder"
      continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Build artifacts
      run: |
        echo "Building release artifacts..."
        mkdir -p artifacts
        echo "Build completed at $(date)" > artifacts/build.log
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: artifacts/