name: CI

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt || pip install fastapi uvicorn requests pydantic python-dotenv
          pip install pytest pytest-cov pytest-asyncio ruff mypy
      - name: Lint with ruff
        run: ruff check src/ --ignore E501
      - name: Type check with mypy
        run: mypy src --ignore-missing-imports || true
      - name: Run tests
        run: |
          pytest tests/ -v --cov=src --cov-report=xml --cov-fail-under=50 || true
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety pip-audit
      - name: Security scan with bandit
        run: bandit -q -r src/ || true
      - name: Check dependencies with safety
        run: safety check --json || true
      - name: Audit packages
        run: pip-audit || true
